[workspace]
members = [
    "graco",
    "examples/web/coarsening",
    "examples/web/coarsening_perf",
    "examples/web/coarsening_recompute_weights",
    "examples/web/match_pairs_by_edge_weight",
    "examples/web/match_pairs_by_edge_weight_2",
    "web-viewer"
]
